/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppApikeyRouteImport } from './routes/_app.apikey'
import { Route as AppMeetingsIdSummaryRouteImport } from './routes/_app.meetings.$id.summary'
import { Route as AppMeetingsIdSetupRouteImport } from './routes/_app.meetings.$id.setup'
import { Route as AppMeetingsIdLiveRouteImport } from './routes/_app.meetings.$id.live'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApikeyRoute = AppApikeyRouteImport.update({
  id: '/apikey',
  path: '/apikey',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsIdSummaryRoute = AppMeetingsIdSummaryRouteImport.update({
  id: '/meetings/$id/summary',
  path: '/meetings/$id/summary',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsIdSetupRoute = AppMeetingsIdSetupRouteImport.update({
  id: '/meetings/$id/setup',
  path: '/meetings/$id/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsIdLiveRoute = AppMeetingsIdLiveRouteImport.update({
  id: '/meetings/$id/live',
  path: '/meetings/$id/live',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/apikey': typeof AppApikeyRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/meetings/$id/live': typeof AppMeetingsIdLiveRoute
  '/meetings/$id/setup': typeof AppMeetingsIdSetupRoute
  '/meetings/$id/summary': typeof AppMeetingsIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/apikey': typeof AppApikeyRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/meetings/$id/live': typeof AppMeetingsIdLiveRoute
  '/meetings/$id/setup': typeof AppMeetingsIdSetupRoute
  '/meetings/$id/summary': typeof AppMeetingsIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/_app/apikey': typeof AppApikeyRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/meetings/$id/live': typeof AppMeetingsIdLiveRoute
  '/_app/meetings/$id/setup': typeof AppMeetingsIdSetupRoute
  '/_app/meetings/$id/summary': typeof AppMeetingsIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/apikey'
    | '/dashboard'
    | '/settings'
    | '/meetings/$id/live'
    | '/meetings/$id/setup'
    | '/meetings/$id/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/apikey'
    | '/dashboard'
    | '/settings'
    | '/meetings/$id/live'
    | '/meetings/$id/setup'
    | '/meetings/$id/summary'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/signin'
    | '/_app/apikey'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/meetings/$id/live'
    | '/_app/meetings/$id/setup'
    | '/_app/meetings/$id/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apikey': {
      id: '/_app/apikey'
      path: '/apikey'
      fullPath: '/apikey'
      preLoaderRoute: typeof AppApikeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings/$id/summary': {
      id: '/_app/meetings/$id/summary'
      path: '/meetings/$id/summary'
      fullPath: '/meetings/$id/summary'
      preLoaderRoute: typeof AppMeetingsIdSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings/$id/setup': {
      id: '/_app/meetings/$id/setup'
      path: '/meetings/$id/setup'
      fullPath: '/meetings/$id/setup'
      preLoaderRoute: typeof AppMeetingsIdSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings/$id/live': {
      id: '/_app/meetings/$id/live'
      path: '/meetings/$id/live'
      fullPath: '/meetings/$id/live'
      preLoaderRoute: typeof AppMeetingsIdLiveRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApikeyRoute: typeof AppApikeyRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppMeetingsIdLiveRoute: typeof AppMeetingsIdLiveRoute
  AppMeetingsIdSetupRoute: typeof AppMeetingsIdSetupRoute
  AppMeetingsIdSummaryRoute: typeof AppMeetingsIdSummaryRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApikeyRoute: AppApikeyRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppMeetingsIdLiveRoute: AppMeetingsIdLiveRoute,
  AppMeetingsIdSetupRoute: AppMeetingsIdSetupRoute,
  AppMeetingsIdSummaryRoute: AppMeetingsIdSummaryRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
